### ISSUE TITLE
Document fix for txs that sometimes fail with "transaction underpriced" 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1026]
**Describe the bug**

In using the eth-predict readme (on Polygon), I sometimes encounter an error "transaction underpriced". What's happening: network rejects the tx because it doesn't think you're paying a high enough gas fee. 

Workaround in predict-eth: if I retry 1-2 times, it usually goes through.

But we need to fix this properly because:
- the workaround is not suitable for fully automated flows
- the workaround is poor UX for manual flows like READMEs
- and what if it doesn't go through, and we need to pay a higher gas fee? It's not so easy within ocean.py right now

**Overall goal**

Get txs through more reliably, more often.

**Proposed solution**

- If the error comes back, try again 1-2 times. 
- If there are still issues, then multiply gas price by e.g. 1.2 and try again. 
- Repeat (multiply by 1.2, try again) until it works, or until e.g. 50 tries done.

**Comment by AnaLoznianu** [comment]
@trentmc I marked this as `Critical` because if users cannot publish/consume via ocean.py it inflicts directly the ETH-Predict challenge. 

For now, we can do this: 
1. There is an environment variable for the gas multiplier. Initially, @calina-c is going to make sure that this variable is correctly used in ocean.py. 
2. In the ETH-Predict mention setting a 2.0 multiplier in ocean.py (@juanpablovs). We don't want to hardcode this as it is used for all the networks.
3. In the second version of ocean.py(with brownie integrated), there is a config through which we can specify the multiplier for each network, and then we can add a bigger polygon default gas multiplier.

**Comment by trentmc** [comment]
Or, simpler yet: only do (3). This is possible if the next eth-predict challenge only starts after ocean.py with brownie is released. We can set challenge dates as such -- I'm iterating with Ray & Andrea on the dates.

Then the only Q is: when will ocean.py with brownie be released? To help on planning towards that, I've set a meeting among you (Ana) & Calina & I to discuss.

**Comment by juanpablovs** [comment]
copy that, since it doesn't make sense to have this replicated and we are doing option 3 I am going to close the issue I opened this morning. If you would prefer to leave it open please let me know and I'll reopen it at once, thanks!

**Comment by AnaLoznianu** [comment]
Oh, good to know this @trentmc :) 
My assumption was that we need to thoroughly test ocean.py + brownie as it includes a big refactoring. If the ETH-PRedict challenge can wait till everything is done and tested we can go on that path. Thank you all!

**Comment by calina-c** [comment]
@trentmc @AnaLoznianu can we close this?
