### ISSUE TITLE
Support custom network 

### ISSUE THREAD

**Issue by dungeonhao** [oceanprotocol/ocean.py#1078]
Currently we're unable to add custom network configuration to the ocean.py 

Will be required to manually hardcode it on example_config.py 
https://github.com/oceanprotocol/ocean.py/blob/a345582b34d431cdf17e6e01418e199c689ee8c6/ocean_lib/example_config.py#L24

**Comment by trentmc** [comment]
I believe that ocean.py already supports your request:
-  "example_config.py" is just that: examples. You can set the values of `config` however you want; it's just a dict. Values are for network name, metadata cache (Aquarius), provider url, and downloads path.
- Configuring the blockchain network RPC url is in brownie (not ocean.py).

Below are details. Please try changing your setup accordingly.

### Detail 1: what brownie sets

The simple README [describes](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/data-nfts-and-datatokens-flow.md#create-your-network-configuration-file) describes how to use brownie to set the network RPC url: 

"""
Create your network configuration file
ocean.py uses brownie to connect to deployed smart contracts. To configure the RPC URLs, gas prices and other settings, create and fill in a network-config.yml in your ~/.brownie folder, or copy our (very basic) sample from ocean.py:

```
mkdir ~/.brownie
cp network-config.sample ~/.brownie/network-config.yaml
```

Please check that you have configured all networks before proceeding. Here is a more complete sample from brownie itself: https://eth-brownie.readthedocs.io/en/v1.6.5/config.html.
"""

### Detail 2: what ocean.py sets

Let's use the ([simple remote README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/simple-remote.md))  example to set up a remote network. Here's the top-level code:

```python
from ocean_lib.web3_internal.utils import connect_to_network
connect_to_network("mumbai")

import os
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config("mumbai")
ocean = Ocean(config)
```

I'll unpack the key lines of `connect_to_network()` and `get_config()`. 

First, `connect_to_network()`. It checks to see if you're already connected to the target network, and if you're not, it takes the steps to get you connected. All by linking together some core brownie network methods. [Code:](https://github.com/oceanprotocol/ocean.py/blob/a345582b34d431cdf17e6e01418e199c689ee8c6/ocean_lib/web3_internal/utils.py#L63)
```python
from brownie import network
...
def connect_to_network(network_name: str):
    if network.is_connected():
        if network.show_active() != network_name:
            network.disconnect()
            network.connect(network_name)
    else:
        network.connect(network_name)
```

Now, let's unpack `ExampleConfig.get_config()`. It's basically a one-liner to `get_config_dict()`. [Code:](https://github.com/oceanprotocol/ocean.py/blob/a345582b34d431cdf17e6e01418e199c689ee8c6/ocean_lib/example_config.py#L77)
```python
    def get_config(network_name=None) -> dict:
        """Return config dict containing default values for a given network.
        Chain ID is determined by querying the RPC specified by network_url.
        """

        if not network_name:
            network_name = "development"

        config_dict = get_config_dict(network_name)

        return config_dict
```

Then, `get_config_dict()` fills in and returns a dict with some good defaults for the specified network. You can change the dict values to whatever you want, of course. [Code:](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/example_config.py)
```python
config_defaults = {
    "NETWORK_NAME": "development",
    "METADATA_CACHE_URI": "http://172.15.0.5:5000",
    "PROVIDER_URL": "http://172.15.0.4:8030",
    "DOWNLOADS_PATH": "consume-downloads",
}
...

CONFIG_NETWORK_HELPER = {
...
    "mumbai": {
        "PROVIDER_URL": "https://v4.provider.mumbai.oceanprotocol.com",
    },
}
...

def get_config_dict(network_name: str) -> dict:
    if network_name not in CONFIG_NETWORK_HELPER:
        raise ValueError("The chain id for the specific RPC could not be fetched!")

    config_helper = copy.deepcopy(config_defaults)
    config_helper.update(CONFIG_NETWORK_HELPER[network_name])
    config_helper["NETWORK_NAME"] = network_name

    if network_name != "development":
        config_helper["METADATA_CACHE_URI"] = METADATA_CACHE_URI
    else:
        config_helper[
            "ADDRESS_FILE"
        ] = "~/.ocean/ocean-contracts/artifacts/address.json"

    return config_helper
```

----

We'd be interested to see how you do once you change your setup accordingly. You can simply report in this issue.

I'm closing this issue because I believe it's already supported according to your request. However if you still encounter issues, please re-open and report. Thank you!

**Comment by dungeonhao** [comment]
Sorry but what if its a new custom network, which is not included in the example_config.py list ? 
Lets say gaiax_network, polygonedge or arbitrium
How can we add that and configure its rpc url, with custom METADATA_CACHE_URI & PROVIDER_URL etc.

**Comment by trentmc** [comment]
Ocean contracts are currently deployed to five production networks and several testnets. The list, and related URIs etc, are here: https://docs.oceanprotocol.com/core-concepts/networks

So if you pointed the RPC url etc to one of those other networks, they wouldn't work because there are no contracts deployed there; and there is no related infrastructure.

For a network to be properly supported, it needs:

- Network is in production (or clearly a testnet)
- EVM support is in production
- ERC20 bridge to Eth mainnet is in production
- OCEAN is on bridge, in production
- RPC (archive node required) available & in production. Eg supported by infura
- RPC is fully web3-compatible

Then finally:
- Ocean deployed (contracts, Aquarius, Provider, TheGraph). Ocean Market tested. Network in Ocean docs

The Ocean core team has an (evolving) list of possible networks to add, with proper support. The three networks you mention fit on that list. It's not a huge effort for team to deploy the contracts and update related infrastructure. However the ongoing effort to maintain the infrastructure does take time.  And, while we had pressure to support some networks, then in practice we have seen zero demand for them. So the core team is stuck maintaining something that no one is using:(

Given this, the core team has focused its energy on other traction-driving activities for now. That said, it's open to deploying to more networks if real demand can be shown. Q's to ask include: what's the benefit compared to just using one of the existing supported networks? If this new network was properly supported, what specific data services (datasets, algorithms) would be published, and will they actually be _used_ ? 

If you would like proper support for one of the networks above, then the best "next step" is to show real demand. The more stark this is, the better.

I hope that helps!
