### ISSUE TITLE
 Change existing ocean.py C2D README, to show how to submit an algorithm for use by C2D easily. (The current C2D README doesn't do this right now, rather.) IIRC, docker containers are involved.

### ISSUE THREAD

**Issue by jfdelgad** [oceanprotocol/ocean.py#1106]
**Describe the bug**
Simplify C2D flow Readme, motivated by [predict-eth](https://github.com/oceanprotocol/predict-eth/issues/54)

**Comment by trentmc** [comment]
The first two goals of [predict-eth#40](https://github.com/oceanprotocol/predict-eth/issues/40) are the following. I just made the phrasing more explicit, to help elucidate the difference between the two.

- "Change ocean.py C2D README, to show how to submit an algorithm for use by C2D including docker container. Github issue."  NOTE: I just created a github issue in ocean.py for this: https://github.com/oceanprotocol/ocean.py/issues/1108
- "Streamline C2D README: remove explicit calls to create data_nft & datatoken; leverage create_url_asset; leverage update_metadata." NOTE: There's been a longstanding github issue for this, that I just tweaked:  https://github.com/oceanprotocol/ocean.py/issues/950

Going back to _this_ github issue: 
- its title aims to do like the first bullet above
- yet its description and the related PR actually do the second bullet above
- and the second bullet above already has an existing github issue: ocean.py # 950. 

To remove confusion: I am closing this ticket (because duplicate), and I will re-point the PR for "this" issue to ocean.py # 950
