### ISSUE TITLE
Add all supported networks configs in the network-config.sample

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#1156]
Add all supported networks in: https://github.com/oceanprotocol/ocean.py/blob/main/network-config.sample
We need to point to the network config from the venv if the config file is not defined. 
Otherwise, we need to create a custom network config for the user
Add this information in the READ.ME

**Comment by AnaLoznianu** [comment]
I had two issues with the network-config when running the eth-predict with the ocean.py setup.

1. After loading the helpers from here: https://github.com/oceanprotocol/predict-eth/blob/main/support/helpers.md, running the ocean = create_ocean_instance() throws this error: 
`Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 4, in create_ocean_instance
File "/Users/.../venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
return func(*args, **kwargs)
File "/Users/.../venv/lib/python3.8/site-packages/ocean_lib/web3_internal/utils.py", line 69, in
connect_to_network network.connect(network_name)
File "/Users/.../venv/lib/python3.8/site-packages/brownie/network/main.py", line 31, in connect active = CONFIG.set_active_network(network)
File "/Users/.../venv/lib/python3.8/site-packages/brownie/_config.py", line 76, in set_active_network network = copy.deepcopy(self.networks[id_])
KeyError: 'polygon'` 
This is because in the default brownie config(network-config.yaml) the polygon network is called 'polygon-main' and not 'polygon'. 
We can reconcile this in two ways: updating the helpers or updating the default network-config.yaml file

2. On the [setup](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/install.md#create-your-network-configuration-file) we have 

`mkdir ~/.brownie
cp network-config.sample ~/.brownie/network-config.yaml`
So, we are trying to override the default brownie network configuration. Why?

cc @trentmc

**Comment by trentmc** [comment]
> So, we are trying to override the default brownie network configuration. Why?

ocean.py (and predict-eth) should use the brownie defaults as much as possible.

And, I believe that was the intent.

If there _is_ some difference, we should fix it. Or if possible, "get out of the way" and not even have `network-config.sample` file.

@calina-c will have more insight into this

**Comment by mariacarmina** [comment]
In the brownie default network-config, we have all the networks ETH networks and also development and polygon related networks, but it doesn't have some networks that we have the contracts deployed on (for example `energyweb`), so at some point the user still needs to manually configure the network-config file. Maybe we can provide a better documentation of how to use or manipulate network configurations from ocean.py. Now that we have `install.md`, we can provide a section just for `how to configure your custom network using brownie in ocean.py`. cc @trentmc 

> So, we are trying to override the default brownie network configuration. Why?
@AnaLoznianu, I think the idea was to let the user create a custom `network-config` file which will override the brownie default one in order to keep only the networks defined by the user.

**Comment by trentmc** [comment]
install.md is not the place for custom networks. It should stay as compact as possible so that new users can proceed on to actually using  Ocean.

If you want Ocean running on a custom network, there's a ton of things you'd need to do. We have documentation elsewhere for that.

> I think the idea was to let the user create a custom network-config file which will override the brownie default one in order to keep only the networks defined by the user.

If this is truly the reason then we definitely shouldn't be overriding it. Eg what if the user was using Brownie before?

Ocean.py needs to take a light touch, vs fully rewriting config files.

**Comment by mariacarmina** [comment]
> If you want Ocean running on a custom network, there's a ton of things you'd need to do. We have documentation elsewhere for that.

By `custom network`, I meant to add a network which is not already defined in the default brownie `network-config.yaml`, such as `energyweb`. We should have support for the networks that we have out contracts deployed on.

**Comment by trentmc** [comment]
> That's why I suggest to include a separate section for these use cases. 

Please, let's not over-complicate this. "User used brownie before" is not special, it's probably already >50% of users and may get to >90% over time.

The install readme is first thing that people see when installing Ocean. So it needs to be as compact as possible. It should not have "advanced" stuff. We can put that elsewhere.

And, let's always bias to having a light touch. No overwriting good defaults by brownie, no "custom" Ocean stuff when brownie is already doing it. It's negative value-add to the user, and adds complexity for us.

### What I recommend

First, _delete_ `network-config.sample`

Then, in the install readme, rather than asking the user to blow up their existing brownie `network-config.yaml` (via the copy command), the install doc can mention something like: 

"""
Your default `network-config.yaml` includes values for most [Ocean-deployed chains](https://docs.oceanprotocol.com/core-concepts/networks). One exception is Energy Web Chain. To support it, add the following to your network-config.yaml` file: 
```
- name: energyweb
  networks:
  - chainid: 246
    host: https://rpc.energyweb.org
    id: energyweb
    name: energyweb
```
"""

FYI, there was a recent github issue "support custom network" [#1078](https://github.com/oceanprotocol/ocean.py/issues/1078#issuecomment-1323842648), where "custom" there meant running Ocean on non-OPF chains. _This_ needs many things done. [Details](https://github.com/oceanprotocol/ocean.py/issues/1078#issuecomment-1323842648).

**Comment by mariacarmina** [comment]
Thanks @trentmc for guidance, I will do the necessary changes to support your approach.
