### ISSUE TITLE
DX win: Replace Web3.toWei(x, "ether") with to_wei(x). Same for fromWei().

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1234]
### Motivation

`Web3.toWei(x, "ether")` is ok. It's used all over ocean.py.

We have a more compact way to express this: `to_wei(x)`. It's half the number of characters. 

Same for `Web3.fromWei()` --> `from_wei()`.

We already have _some_ use of `to_wei` and `from_wei` but not everywhere.

### TODO for this issue

- Replace calls to `Web3.toWei()` with `to_wei(x)`
- Replace calls to `Web3.fromWei()` with `from_wei(x)`

This is a simple, easy win:)

**Comment by calina-c** [comment]
@trentmc Would you consider removing to_wei altogether? I think brownie can do these conversions by itself. However, when we added brownie, we used to have those complex structures that mirrored all the contract functions. Those were `@enforce_type`d with our own ideas of what those arguments should be. However, if the underlying structure can accept and convert e.g. "1 ether" instead of having us do the conversions beforehand, shouldn't we consider that option? I'll investigate it more thoroughly today but I think it's much better than using wei conversions :)

**Comment by trentmc** [comment]
We use conversions to and from wei everywhere. Therefore I want them:

1. compact. 5 characters is better than 10. Etc.
2. low cognitive load. In Brownie, if I see eg "3 eth", it's cognitive load because I have to re-remember each time that it's not ETH per se, it could be OCEAN or a DT or something else. Whereas calls like "to_wei()" and back are much more obvious.
3. easy to work with floats, without needing to muck around with decimals (as long as I get the precision I need for the use case)
4. reliable 

Imo we only get all 4 with the simple to_wei() and from_wei() functions.
