### ISSUE TITLE
In the remote setup readme, we point users to the brownie-config instead of the netweork config

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean.py#1263]
In the [remote setup](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/setup-remote.md#11-configuration-file) readme, we have this: "[Here's](https://eth-brownie.readthedocs.io/en/v1.6.5/config.html) the network-config.yaml from Brownie docs. It can serve as a comparison to your local copy." but the link actually sends the user to the brownie-config.yaml file not to the network-config file.

**Comment by calina-c** [comment]
Here's the problem with this: newer brownie versions use brownie-config.yaml, while the old network-config.yaml is still a valid option for configuring networks. I thought the link was incorrect, but here are our options:
- keep it as such -> works because the options in that brownie-config.yaml can easily be set in a network-config.yaml and it is the most complete example of configuration available
- link to an older version of the brownie docs, where network-config and not brownie-config is presented as an example -> I think this would confuse users as to the brownie version we are indeed using.
- create our own example file -> we used to have this but it turned out problematic, since it required copy and pasting during CI, and adding a layer of inflexibility: the user can have their own network-config for multiple projects, we can not simply override their file

Also to keep in mind:
- we can not ground a proper brownie version yet, until they resolve Python 3.11 dependencies. That is why in our setup.py we do not set a brownie version. I have opened a PR on the brownie repo in this case. Once we do ground to a brownie version, there is more leeway in switching to brownie-config instead of network-config, if needed.

@AnaLoznianu what do you think? I'm thinking of closing this issue, but please let me know if you want me to reword anything in the readme to make it more clear, or do any changes.

**Comment by AnaLoznianu** [comment]
Thanks for looking into this @calina-c. If it works as it is right now and users can pick options from the brownie-config and set them in the network-config then there is no problem.
