### ISSUE TITLE
start compute should accept multiple DIDs

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/ocean.py#130]
https://github.com/oceanprotocol/ocean.py/blob/23274698df4aae078d53b12d768c721af16f6e80/ocean_lib/ocean/ocean_compute.py#L179

**Comment by trentmc** [comment]
@0x3bfc please specify this issue better. Here's the template.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by alexcos20** [comment]
we already have this in https://github.com/oceanprotocol/ocean.py/issues/131
