### ISSUE TITLE
Get all pre-commit issues passing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#172]
**Is your feature request related to a problem? Please describe.**
Calina recently intro'd the optional use of the [pre-commit tool](https://pre-commit.com/) into developers.md. It's cool!

If you use it when you're doing a commit, it will check the files that you've changed in your commit.

However you can also run it against the whole existing codebase via:
```console
pre-commit run --all-files
```

I tried this! It changed about 6 files, and had a few failures. It would be good for pre-commit to be fully happy about the existing codebase, it will help us to move forward with less friction.

**Describe the solution you'd like**

Run `pre-commit run --all-files`. Commit the changes it's made (once unit tests pass). Then fix all the issues it reports (and ensure unit tests etc keep passing).

**Comment by calina-c** [comment]
All the pre-commits have been run first on the entire codebase and both black and flake8 are required checks as GitHub actions. The reason for the pre-commit is so that you already have a local way of bumping into potential problems from the GitHub actions checks. This means that the failures you found are due to people not using pre-commit before (it was in the docs), merging branches without passing Github Actions, or simply conflicts/automatic merges by git.

I'll take a look later to see if everything is correctly mirrored from pre-commit checks to Github actions checks (I believe aquarius might not have the isort tool) and do a correction on all repos.
