### ISSUE TITLE
release process has 11 steps, making it cumbersome

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#179]
**Is your feature request related to a problem? Please describe.**

Thanks to #118, ocean.py's release process is now documented, in https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/release-process.md

But it has 11 steps! This makes it cumbersome.

We can do better. For example, the [release process in ocean.js](https://github.com/oceanprotocol/ocean.js#-production) has automated most of the steps behind one simple command in the above example. "If the release process requires more than 3 steps, please automate it." 

(Note: adapted @kremalicious' comments for the above description)

**Describe the solution you'd like**
Get ocean.py's release process to <= 3 steps.

**Comment by akshay-ap** [comment]
For release steps here: https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/release-process.md.
1. I think steps 1 to 5  can be automated with a shell script.
2. We can use this lib to generate change log https://github.com/KeNaCo/auto-changelog.
What do you think @kremalicious  @ssallam?

**Comment by kremalicious** [comment]
sure, whatever works and backend team agrees upon, since it should be standardized across all backend repos in the end.

As for steps, just some input: on the js repos we automate away [a lot of the steps](https://github.com/oceanprotocol/ocean.js#%EF%B8%8F-releases) and changelog is just one step. This is done with a library [release-it](https://github.com/release-it/release-it) and ideally we find something like that for the Python world.

The goal is to have version file/git tag/GitHub release/changelog synced at all times. We choose a compromise and essentially push to `main` for releases since only that makes it possible to have the tagged release commit include the newly auto-generated changelog.

**Comment by akshay-ap** [comment]
@kremalicious I am thinking of generating the changelog and automating the release process through a script like this: 
https://github.com/akshay-ap/ocean.py/blob/feature/release-process/release.sh. 

Sample generated from the script: https://github.com/akshay-ap/ocean.py/blob/feature/release-process/CHANGELOG.md

The script is not yet complete. It is just to show how I plan to do it.
