### ISSUE TITLE
data_token.py ERC20 functionality doesn't reflect ERC20 interface

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#228]
**Problems**

Datatokens implement the ERC20 interface, and tack on a couple more pieces of functionality. 

This is exactly the case in the smart contract level: [DataTokenTemplate inherits ERC20](https://github.com/oceanprotocol/contracts/blob/master/contracts/templates/DataTokenTemplate.sol). Good.

But [data_token.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/data_token.py) does _not_ reflect it cleanly:
- Its ERC20 interface should reflect those of the smart contract. But it doesn't. When we wrote the ocean.py alpha in mid 2020, it had just a subset, more for reasons of speed of implementation. But then new methods were added in an ad-hoc fashion; those new methods break the principle. 
- For example, get_info() returns name, symbol and more as a single function :/ . This was first introduced as [this PR](https://github.com/oceanprotocol/ocean.py/pull/74) with [this commit](https://github.com/oceanprotocol/ocean.py/commit/26f241eb12da750767c0d4088e44521a7a943cdb)). This is non-standard. It's also a poor OO interface: each getter should focus on a single piece of info, just as the smart contract level.

**Proposed Solution**

Ensure that the interface for data_token.py's ERC20 functionality is the same as the underlying smart contract. Like how bpool.py does it. 

**Tips**

- We can likely have it inherit from BToken.py which is an ERC20 python interface. 
- Or perhaps make it directly use [web3.py ERC20 functionality](https://web3py.readthedocs.io/en/stable/examples.html#working-with-an-erc20-token-contract). To be explored:)

**Notes**
- Doing _this_ issue will help towards #231 "base type conversions" because it will deprecate interfaces that break base18.

**Comment by DMats** [comment]
>Doing this issue will help towards #231 "base type conversions" because it will deprecate interfaces that break base18.

Agreed. I've self-assigned this issue and intend to complete it before continuing with #231.

**Comment by DMats** [comment]
>**Proposed Solution**
>
>Ensure that the interface for data_token.py's ERC20 functionality is the same as the underlying smart contract. Like how bpool.py does it. 
>
>**Tips**
>
>- We can likely have it inherit from BToken.py which is an ERC20 python interface. 
>- Or perhaps make it directly use [web3.py ERC20 functionality](https://web3py.readthedocs.io/en/stable/examples.html#working-with-an-erc20-token-contract). To be explored:)

Adding functions that exist in [DataTokenTemplate.sol](https://github.com/oceanprotocol/contracts/blob/master/contracts/templates/DataTokenTemplate.sol) but are missing in [data_token.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/data_token.py) was relatively easy and has been completed in https://github.com/oceanprotocol/ocean.py/commit/46dc3ece562cee6bb763a749e742585ee8f1c320. (I plan to do more clean-up 

I'll be working on removing methods like `get_info()` next. It will be a little more difficult because it requires investigation into why each method was added, what currently uses them, and the impact of removing them, etc. `bpool.py` is very clean compare to `data_token.py`

**Comment by trentmc** [comment]
+1 so far:)

**Comment by DMats** [comment]
A quick note I forgot to include in my last comment:

>We can likely have it inherit from BToken.py which is an ERC20 python interface.

I decided not to inherit from BToken because the 6 functions defined in BToken.py are not the same 6 functions required by the [ERC20 spec](https://eips.ethereum.org/EIPS/eip-20). BToken.py defines 3 of the 6 required functions and the 3 optional functions defined in the ERC20 spec.

Adding to the confusion, I just realized that my last commit https://github.com/oceanprotocol/ocean.py/commit/46dc3ece562cee6bb763a749e742585ee8f1c320 is missing the non-standard functions defined by the [OpenZeppelin ERC20.sol (version 2.5.0)](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/token/ERC20/ERC20.sol) so I'll make sure to add those as well.

**Comment by DMats** [comment]
I finished removing the `DataToken.get_info()` method.  I ended up adding a `DataToken.calculate_token_holders()` method to eliminate some duplication in `ocean_pool.py`

After briefly surveying all the other methods, I think they can probably stay.  Some of them will be removed in #231. Others are useful for processing events. and the rest are wrappers for the underlying smart contract.

I'll work on adding unit tests next week.  

I think I'm on track to finish before the end of the sprint.

**Comment by DMats** [comment]
After reviewing the unit tests at [DataTokenTemplate.Test.js](https://github.com/oceanprotocol/contracts/blob/main/test/unit/datatokens/DataTokenTemplate.Test.js) I think it maybe doesn't make sense to add nearly identical unit tests in ocean.py. So I'll go ahead and submit the PR.
