### ISSUE TITLE
Add ocean.assets.isConsumable

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#298]
This function should check if the asset is consumable by :
- check isDisabled flag (it exists & true -> asset is not consumable)
- check file conectivity
- check credentials

Return should be a interface, containing a status and a status_message: Eg
   0, All good
   1, Asset is disabled
   2, Connectivity check failure
   3, Credential missing from allow list
   4, Credential found on deny list

**Comment by calina-c** [comment]
Should we name this isConsumable, and does it refer to the same concept as the Aquarius `isConsumable` that we are now trying to remove?

**Comment by calina-c** [comment]
@alexcos20 should there be a "short-circuit" type check of isConsumable? Ref. "connectivity check": that will only circle back to Provider, when called FROM Provider. So at least on provider, we can check the connectivity right there, with the in-built helpers, instead of circling through ocean_lib calling to the provider endpoint.

**Comment by alexcos20** [comment]
yes, we have different flows, depending on the component.
but provider already does pingCheck
