### ISSUE TITLE
Add CI/CD pipeline and badge to the repository that verifies tests are passing.

### ISSUE THREAD

**Issue by LinuxIsCool** [oceanprotocol/ocean.py#418]
**Is your feature request related to a problem? Please describe.**
Lacking CI/CD tests

**Describe the solution you'd like**
CI/CD that runs tests and renders passing badge

**Describe alternatives you've considered**
Running tests to find that they fail.

**Additional context**
I'm getting an error when I go through the simple flow. Then I went through the developer flow and found that tests are not passing. It would be nice to have a tests verification upon pull requests. 

![image](https://user-images.githubusercontent.com/31582215/127602333-1c79a6cc-c7f9-4fb7-b63b-0ffa7eeae142.png)

I've seen  @JohannSuarez implement this for repos at [LTF](github.com/longtailfinancial) - I'll invite him to make a pull request here as well.

**Comment by calina-c** [comment]
Hi, @LinuxIsCool !
We do have this. Please check out the readme here, there are badges from Code Climate: https://github.com/oceanprotocol/ocean.py/ 

We also employ CI checks for formatting (using black), PR and branch push test runs, maintainability and test coverage through Code Climate.

Because we have a dynamic team and we keep improving things in preparation for new features, sometimes things in the README can become outdated due to human error. Can you let me know: the ocean_lib version you are using and any relevant configs + the errors you encountered with the simple and developer flows? Thank you!

**Comment by calina-c** [comment]
@LinuxIsCool I'll close this issue for lack of input, the badges are there. If you have more details to add, feel free o reopen or create another issue for the simple flow, if it is still a problem with newer versions.
