### ISSUE TITLE
[EPIC] Refactor ocean.py architecture: unify Asset and DDO classes, more

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#520]
Note: this ticket was initially a discussion about whether to re-boot ocean.py or refactor it. That discussion happened, and the choice is to refactor it. 

Here's the current list by Calina from [this comment](https://github.com/oceanprotocol/ocean.py/issues/520#issuecomment-938491658).

They are all currently _proposals_. It may be that we don't do some of them, it will be a judgement call as we proceed. 

* unify Asset and DDO classes. If we need to separate some code just for readability purposes, let's create mixins that deal with different aspects of the DDO. Right now, it is confusing to have two classes dealing with the same concept. E.g. Asset is a child of DDO, and it also defines trusted algo functions. What if I am using a DDO and I want to add trusted algorithms? I have to use the Asset base class instead, and it's cumbersome to figure this out.
* move create_checksum out of assets/utils.py and rename the file to trusted_algorithms.py (create_checksum is the only outlier) -> perfect place for create_checksum is in utilities.py, right NEXT TO checksum()
* move contents of common/agreemeents outside: it now contains fewer things (after Service refactoring), and if we unify Asset and DDO, it will be even lighter and easier to move
* remove AquariusProvider… simply retrieve the Aquarius class based on the config
* move ddo/constants.py contents to agreements
* convert AddressCredential class into a mixin -> keeps the code separate, but makes it more flexible
* common/ddo/README.md -> either move it to READMEs, or remove it entirely (it is leftover from the plecos, as its original README.md)
* investigate DID.py, it probably needs some attention
* Data Service Provider (there is already a ticket for this: #471)

**Comment by trentmc** [comment]
This is new. And a big decision. Please share context / info. Specifically:
- what are the specific concerns of the current ocean.py
- Please document pros and cons of keeping the current codebase versus a new one.

I always fear "second system syndrome". It bit me once early in my career. I acknowledge that sometimes it is appropriate.

**Comment by calina-c** [comment]
> This is new. And a big decision. Please share context / info. Specifically:
> 
> * what are the specific concerns of the current ocean.py
> * Please document pros and cons of keeping the current codebase versus a new one.
> 
> I always fear "second system syndrome". It bit me once early in my career. I acknowledge that sometimes it is appropriate.

Hi, Trent! We discussed this during our last backend grooming session. Here's are the main arguments for a new v4 version of ocean.py:
- symmetry with ocean.js, which is also being rewritten
- the new DDO structure that needs support in v4: it is difficult to maintain two different structures at once
- stale aspects in services, service descriptors etc., which are leftovers since v1 and are either obsolete or poorly used/handled (I discovered some of these during the removal of ocean-lib from provider)
- flows need to be completely redone in v4: so if the basics need some shape-up and structural changes, and the flows need to be fully redesigned, we agreed it's warranted to do this.

last but, not least, this is perhaps the most half-fleshed idea on this list, because it's somewhere in my brain but I have to put it in some schematics/run some tests to prove it:
- code smells: both me and Maria spent so much time trying to copy over new contracts from v4. I think there is a smarter way to integrate contracts, where we could perhaps autodetect methods and parameters, or just have a simple configuration class that creates the necessary object classes.

**Comment by trentmc** [comment]
Hi Calina,

Thanks for the thoughts. I appreciate seeing this written down.

Let's review the concerns.

> symmetry with ocean.js, which is also being rewritten

First, a pure logic point: Just because driver A is getting rewritten does not mean we should rewrite driver B. 

Next, ocean.js is way more monolithic. It never got the refactors over the last 6 months that ocean.py did. 

Furthermore, we should not expect ocean.js and ocean.py to be the same in the future either. 
- They might support the same base flows as drivers for the solidity code and with datatokens + marketplace quickstart. 
- Beyond that they we should expect them to significantly. Here's why. >90% of data science is in python, <0.1% is in JS. Accordingly, ocean.py will support for fancier flows like C2D README doing data science or visualization. You'd never see such a flow for ocean.js.

> the new DDO structure that needs support in v4: it is difficult to maintain two different structures at once

Most of ocean.py does not care at all about how DDO is shaped, it's only in one corner of the code. Which means that changes to DDO structure only affect ocean.py in small surgical places.

> stale aspects in services, service descriptors etc., which are leftovers since v1 and are either obsolete or poorly used/handled (I discovered some of these during the removal of ocean-lib from provider)

These have not been holding back ocean.py so far. Which means we can simply remove or fix these in an evolutionary fashion. Deleting = a lot easier than rewriting.

> flows need to be completely redone in v4

By flows do you mean the quickstart READMEs? Assuming this, then (1) flows don't need to be redone and (2) even if they did, it's only surface level. Details:
1. The NFT part is tweaks on how data assets are created. It's a few lines change to any given README. 
2.  Flows are in READMEs, which are surface level and very malleable. We already shift these around as we need. Changing these flows does not mandate changing the whole library below. 

> both me and Maria spent so much time trying to copy over new contracts from v4. 

The core architecture is: for each .sol file, have a corresponding .py module acting as a driver. All py module drivers are in one place: [ocean_lib/models](https://github.com/oceanprotocol/ocean.py/tree/main/ocean_lib/models). As we were evolving V3 contracts, I was able to readily evolve those modules. 

I don't see why there would be any issues doing this for v4 as well.

> I think there is a smarter way to integrate contracts, where we could perhaps autodetect methods and parameters, or just have a simple configuration class that creates the necessary object classes.

We thought about doing this for V3. And we chose not to, for the following reasons.
- Small / simple code. They're mostly just one-liner 1:1 mappings of the contract code, plus docstrings.
- Good interface. Having the .py files explicitly define the interface for other python modules to use. The docstrings are actually 2/3 of the code in a given module. Docstrings here are way better documented than the contract code (much lifted from Balancer). 
- Unit tests. You still need unit tests, to ensure it all fits together. For every actual driver line there are two lines of unit tests.
- Low maintenance needs. The contracts code doesn't evolve, and the modules haven't had the need for much evolution either. Unit tests were thorough from day 1. Look at it, the only changes you'll see are little tweaks here on formatting, etc.

----
As a reminder: second-system syndrome is the idea of "redoing something" because the the engineers are striving for something perfect, and in the end it blows out the schedule by 2x or 4x or more. It happened to my first startup, we lost a whole _year_ in shipping our V2. What we should have done is simply kept refactoring, one step at a time, diligently, towards the goal. We would have done it in far less time, and with far less risk.

To quote Chad Fowler: "Beware. This is a longer, harder, more failure-prone path than you expect." [link](https://web.archive.org/web/20161208161441/http://chadfowler.com/2006/12/27/the-big-rewrite.html)

--

Summary:
- The concerns listed not sufficient to redo ocean.py, especially given the massive risk of second system syndrome.  
- If it ain't broken, don't fix it. And, refactoring is a power tool.

**Comment by calina-c** [comment]
Thank you, Trent! Your points make sense to me. It's possible I've missed some points we discussed yesterday, but I tried to cover most of them. I think we should have some input from @DMats and @alexcos20 too, since they were also in favour of rewriting it entirely. I myself am torn.

**Comment by trentmc** [comment]
> I myself am torn.

Given my response, why are you torn?

**Comment by trentmc** [comment]
Some more fun quotes.

----
[Jo Van Eyck](https://www.ae.be/blog-en/big-rewrite/) "The Big Rewrite"

Does the term "rewrite" scare the bejeezus out of you? Good. It should. A rewrite is not something to be taken lightly and should be your very last resort. There are less painful routes you can take, but what if there really is no valid alternative to "The Big R"?

..

In case I have not made myself abundantly clear: a big rewrite will cost you more than you bargained for. There is no guarantee the new system will result in an improved situation. Every greenfield effort starts with high expectations and most of them are unable to hold up to their initial ideals. It might be economically more interesting to work from what you have and incrementally massage it into a more maintainable solution rather than throwing it all away and starting over. 

----
[Joel on Software](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/) "Things You Should Never Do, Part 1"

The last major release, version 4.0, was released almost three years ago. Three years is an awfully long time in the Internet world. During this time, Netscape sat by, helplessly, as their market share plummeted.

It’s a bit smarmy of me to criticize them for waiting so long between releases. They didn’t do it on purpose, now, did they?

Well, yes. They did. They did it by making the single worst strategic mistake that any software company can make:

They decided to rewrite the code from scratch.

Netscape wasn’t the first company to make this mistake. Borland made the same mistake when they bought Arago and tried to make it into dBase for Windows, a doomed project that took so long that Microsoft Access ate their lunch, then they made it again in rewriting Quattro Pro from scratch and astonishing people with how few features it had. Microsoft almost made the same mistake, trying to rewrite Word for Windows from scratch in a doomed project called Pyramid which was shut down, thrown away, and swept under the rug. Lucky for Microsoft, they had never stopped working on the old code base, so they had something to ship, making it merely a financial disaster, not a strategic one.

We’re programmers. Programmers are, in their hearts, architects, and the first thing they want to do when they get to a site is to bulldoze the place flat and build something grand. We’re not excited by incremental renovation: tinkering, improving, planting flower beds.

----
[James Shore](http://www.jamesshore.com/v2/blog/2006/how-to-survive-a-rewrite) "How to Surive a Software Rewrite"

Rewrite projects are tempting and dangerous. They're tempting because they always look easier than they actually are. They're dangerous because you can't release the new software until you've completely replicated the functionality of the old software.

That's a lot longer than you expect. Meanwhile, you're spending tons of money, you're getting no new revenue, and your old product is falling further and further behind the competition/user needs. This leads to pressure, which usually leads to throwing out all the good software practices that were the reason for the rewrite in the first place.

If you want to survive a software rewrite, don't throw away your existing software. Instead, identify what it is about the new software that's going to be valuable to your customers/users. Work on those pieces first. Write the code in such a way that it co-exists with your existing software, perhaps as an optional add-on that you can sell.

If you're not changing core technologies (language or platform), refactor your existing code as you work with it. Some pieces might be cheaper to rewrite than to refactor, but don't jump to that conclusion. Instead, take it on a case-by-case basis and when you do rewrite, keep the pieces small and timebox the effort to days, not weeks.

**Comment by trentmc** [comment]
> But we need to get rid of old code that still lies around (ie: Service Agreements)

Absolutely, this is simply a refactor in the right places (not so risky). That's a very different than a rewrite (very risky).

**Comment by AnaLoznianu** [comment]
@calina-c Can we close this? I see a merged PR

**Comment by calina-c** [comment]
@AnaLoznianu there is a merged PR but it doesn't handle everything. And for the past few days I've been busy with aqua and provider. Maria also did some improvements on the trusted algorithms utility, so I'll check and see if we need to do more.

**Comment by calina-c** [comment]
Closing since v4 has an updated architecture and we've checked the remaining tasks from this list organically, while working on others.
