### ISSUE TITLE
Fix setup for READMEs

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#652]
Right now, in the READMEs the setup is an intermediary one which includes next steps:

- grab the ocean.py repo and checkout with v4main branch;
- copy the artifacts folder into the work folder (test3)
- run a script that install the ABIs into the venv of test3 folder

This tweak should be removed from the setup.

**Comment by AnaLoznianu** [comment]
Use the V4 contracts new alpha release

**Comment by calina-c** [comment]
TODOs here:
- [ ] remove the local artifacts folder and the artifacts/install.sh or install-remote.sh
- [ ] use the alpha contracts release. Currently the former contracts version is commented out in setup.py. Run pip install and retest that everything is fine.
- [ ] remove the artifacts copying from the tox workflow, get to a green CI status without the artifacts copying
- [ ] create a local python library without publishing it to pypi
- [ ] test that library separately, outside the ocean.py repo folder on your computer
- [ ] edit all the readmes to contain the correct setup instructions using the library installation. For readmes that are still in v3 mode, there will probably be only a few changes. For the readme containing artifacts copying installation, remove those references.

the ocean.py task will take the longest due to constraints on library creation, installation and readmes.

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/652?planning-poker) with ZenHub @md0x

**Comment by calina-c** [comment]
Currently, the contracts package has the file structure as well. We only need the artifacts as jsons in the root of the package.

Otherwise our only option is the volatile one where we also define the filepath inside each contract class. This is not a good solution, since it would tie up the ocean.py logic to the contracts package structure.

Marking this and the others similar tasks as blocked.
