### ISSUE TITLE
Remove service_endpoint parameters from DataServiceProvider

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#680]
Currently the DSP has methods that take in a service_id and a service_endpoint, but that information is available on the service object itself. Please pass in the Service object entirely. Use build_endpoint only inside DSP, in each function as intended. i.e. in the download function we call build_download_endpoint etc. All these calls will be based on the service endpoint.

Remove all instances where we compute the service_endpoint _outside_ and pass the parameter to DSP. DSP should be smart enough to figure it out. Please remember to adjust all tests and readmes accordingly.

**Comment by mariacarmina** [comment]
I think the reason why both `service_id` and `service_endpoint` are passed is because you cannot import Service in the DSP class, otherwise it will cause an ImportError due to circular imports. Should we create like a "middleware" class between Service and DSP? I tried also these options from [here](https://stackoverflow.com/questions/5748946/pythonic-way-to-resolve-circular-import-statements) and it didn't seem to work.
