### ISSUE TITLE
Add a separate section in each README for using createNftErc type functions

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#693]
There are couple of functions in `erc721_factory` that can be added in READMEs:

- `create_nft_with_erc` for `datatokens.md`
- `create_nft_erc_with_pool` for `marketplace-flow.md`
- `create_nft_erc_with_fixed_rate` for `fixed-rate-exchange.md`
- `create_nft_erc_with_dispenser` for `dispenser-flow.md`

**Comment by trentmc** [comment]
Related: "create_nft_with_erc" and similar labels are nonsensical #707

**Comment by mariacarmina** [comment]
I wanted to match the contract names for these functions, but replace with underscore. Check here as well https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/ERC721Factory.sol#L607.

**Comment by trentmc** [comment]
> There are couple of functions in erc721_factory that can be added in READMEs:

Could you specify _how_ they could be added in READMEs? 

We don't want the READMEs to bloat arbitrarily with every method under the sun.

Looking at the PR (https://github.com/oceanprotocol/ocean.py/pull/704) it looks like exactly this is happening. Huge DRY violation too.

What I recommend:
1. Wait for all the other README PRs to get merged first (it looks like chaos right now)
2. Keep datatokens-flow.md as is, where ERC721 and ERC20 are created separately, so that user sees what's going on.
3. For all the others, use the appropriate method that combines things. Keeps the READMEs shorter.

**Comment by trentmc** [comment]
> I wanted to match the contract names for these functions, but replace with underscore. Check here as well 
> ttps://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/ERC721Factory.sol#L607.

That's out of scope of _this_ issue. Please move discussion to #704

**Comment by trentmc** [comment]
> We don't want the READMEs to bloat arbitrarily with every method under the sun. Looking at the PR (#704) it looks like exactly this is happening. Huge DRY violation too.
> 
> What I recommend:
> 1. Wait for all the other README PRs to get merged first (it looks like chaos right now)
> 2. Keep datatokens-flow.md as is, where ERC721 and ERC20 are created separately, so that user sees what's going on.
> 3. For all the others, use the appropriate method that combines things. Keeps the READMEs shorter.

cc @calina-c

**Comment by calina-c** [comment]
All right, keeping it open for now, until all others are merged. However, it is important to showcase these, since users pay less gas for "at once" deployment of nft+erc or nft+erc+pool/fre/dispenser. I would suggest, as I did in the PR, adding a section called "Advanced token and object creation" where we would just mention these functions and the arguments they take, as an option. Just the functions and call samples, not full onset flows. That's my opinion. Do you agree @trentmc?

**Comment by trentmc** [comment]
> All right, keeping it open for now, until all others are merged. However, it is important to showcase these, since users pay less gas for "at once" deployment of nft+erc or nft+erc+pool/fre/dispenser. I would suggest, as I did in the PR, adding a section called "Advanced token and object creation" where we would just mention these functions and the arguments they take, as an option. Just the functions and call samples, not full onset flows. That's my opinion. Do you agree @trentmc?

READMEs shouldn't give several options all over the place, it makes it confusing. Rather, it should be just one straightforward flow. That flow should be the least code to accomplish the thing. 

In the case here, use the appropriate method that combines things.

(This is better than a section "advanced token and object creation" imo)

**Comment by mariacarmina** [comment]
Should we use for example `create_nft_erc_with_pool` in marketplace-flow.md instead of the flow that is currently in the README? @trentmc

**Comment by mariacarmina** [comment]
I am a bit confused because I thought that the user should be aware of all the possibilities and let him choose which method prefers.

**Comment by mariacarmina** [comment]
UPDATE: Write a short sentence about this alternative and just mention the helpful functions.
